// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bones.Api.Client.AutoGen.ProjectSearch.ByOwner
{
    /// <summary>
    /// Builds and executes requests for operations under \ProjectSearch\by-owner
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class ByOwnerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByOwnerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ProjectSearch/by-owner?ownerType={ownerType}{&organizationId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ByOwnerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ProjectSearch/by-owner?ownerType={ownerType}{&organizationId*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the projects for the current user, or specified organization
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwner400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerGetResponse?> GetAsync(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder.ByOwnerRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwner400Error.CreateFromDiscriminatorValue },
                { "401", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerGetResponse>(requestInfo, global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the projects for the current user, or specified organization
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder.ByOwnerRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bones.Api.Client.AutoGen.ProjectSearch.ByOwner.ByOwnerRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the projects for the current user, or specified organization
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
        public partial class ByOwnerRequestBuilderGetQueryParameters 
        {
            /// <summary>The ID of the organization, if applicable</summary>
            [QueryParameter("organizationId")]
            public Guid? OrganizationId { get; set; } = default!;
            /// <summary>The type of owner, User if self</summary>
            [QueryParameter("ownerType")]
            public global::Bones.Api.Client.AutoGen.Models.OwnershipType OwnerType { get; set; } = default!;
        }
    }
}
#nullable restore
#pragma warning restore CS0618
