---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      core:
        patterns:
          - "Aspire.Hosting.AppHost"
          - "Autofac"
          - "Autofac.*"
          - "DnsClient"
          - "FluentValidation"
          - "FluentValidation.*"
          - "GeoJSON.Text"
          - "MediatR"
          - "MediatR.*"
          - "Microsoft.*"
          - "Npgsql.EntityFrameworkCore.PostgreSQL"
          - "Npgsql.EntityFrameworkCore.PostgreSQL.Design"
          - "OpenTelemetry.*"
          - "Serilog"
          - "Serilog.*"
        exclude-patterns:
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.AspNetCore.Components.WebAssembly"
          - "Microsoft.AspNetCore.Components.WebAssembly.*"
      frontend:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.AspNetCore.Components.WebAssembly"
          - "Microsoft.AspNetCore.Components.WebAssembly.*"
          - "MudBlazor"
          - "CodeBeam.MudBlazor.Extensions"
          - "NSwag.ApiDescription.Client"
          - "Swashbuckle.*"
      testing:
        patterns:
          - "Shouldly"
          - "Microsoft.NET.Test.Sdk"
          - "xunit"
          - "xunit.*"
          - "coverlet.collector"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Pipeline:
        patterns:
          - "*"
