// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.WorkItem.ActionNamespace;
using Bones.Api.Client.AutoGen.WorkItem.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.WorkItem
{
    /// <summary>
    /// Builds and executes requests for operations under \WorkItem
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class WorkItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The action property</summary>
        public global::Bones.Api.Client.AutoGen.WorkItem.ActionNamespace.ActionRequestBuilder Action
        {
            get => new global::Bones.Api.Client.AutoGen.WorkItem.ActionNamespace.ActionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.WorkItem.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.WorkItem.Item.WithWorkItemItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.WorkItem.Item.WithWorkItemItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("workItemId", position);
                return new global::Bones.Api.Client.AutoGen.WorkItem.Item.WithWorkItemItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.WorkItem.WorkItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/WorkItem", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.WorkItem.WorkItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/WorkItem", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
