// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.TaskQueue.CreateInInitiative;
using Bones.Api.Client.AutoGen.TaskQueue.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.TaskQueue
{
    /// <summary>
    /// Builds and executes requests for operations under \TaskQueue
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class TaskQueueRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The createInInitiative property</summary>
        public global::Bones.Api.Client.AutoGen.TaskQueue.CreateInInitiative.CreateInInitiativeRequestBuilder CreateInInitiative
        {
            get => new global::Bones.Api.Client.AutoGen.TaskQueue.CreateInInitiative.CreateInInitiativeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.TaskQueue.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.TaskQueue.Item.WithTaskQueueItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.TaskQueue.Item.WithTaskQueueItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("taskQueueId", position);
                return new global::Bones.Api.Client.AutoGen.TaskQueue.Item.WithTaskQueueItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.TaskQueue.TaskQueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskQueueRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TaskQueue", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.TaskQueue.TaskQueueRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TaskQueueRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TaskQueue", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
