<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <!-- Build info -->
      <TargetFramework>net9.0</TargetFramework>
      <LangVersion>latest</LangVersion>
      <OutputType>Library</OutputType>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <IsPackable>false</IsPackable>
      <IsPublishable>false</IsPublishable>

      <!-- Assembly info -->
      <VersionPrefix>0.0.1</VersionPrefix>
      <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
      <Authors>Nickolas Gupton</Authors>
      <RepositoryUrl>https://github.com/CorruptComputer/Bones</RepositoryUrl>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
      <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
      <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
      <SourceRevisionId>develop</SourceRevisionId>
    </PropertyGroup>

    <!-- This seems like it could be useful -->
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
      <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <!-- If building in release mode, replace the SourceRevisionId with the 8 character git commit hash -->
    <Target Condition="$(Configuration) == 'Release'" Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
      <Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8" ConsoleToMSBuild="True" IgnoreExitCode="False">
        <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
      </Exec>
    </Target>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Testing" Version="9.5.1" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Services\Bones.AppHost\Bones.AppHost.csproj" />
      <ProjectReference Include="..\..\Bones.Testing.Shared\Bones.Testing.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="TestOperations/" />
    </ItemGroup>

</Project>
