// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bones.Api.Client.AutoGen.GenericItem.Item.Layouts
{
    /// <summary>
    /// Builds and executes requests for operations under \GenericItem\{projectId}\layouts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class LayoutsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/GenericItem/{projectId}/layouts{?layoutUse*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/GenericItem/{projectId}/layouts{?layoutUse*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the item layouts for a project, optionally filtered by the uses they are enabled for
        /// </summary>
        /// <returns>A List&lt;global::Bones.Api.Client.AutoGen.Models.GetProjectLayoutsResponse&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<List<global::Bones.Api.Client.AutoGen.Models.GetProjectLayoutsResponse>?> GetAsync(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder.LayoutsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Bones.Api.Client.AutoGen.Models.GetProjectLayoutsResponse>(requestInfo, global::Bones.Api.Client.AutoGen.Models.GetProjectLayoutsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Gets the item layouts for a project, optionally filtered by the uses they are enabled for
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder.LayoutsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the item layouts for a project, optionally filtered by the uses they are enabled for
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
        public partial class LayoutsRequestBuilderGetQueryParameters 
        {
            [Obsolete("This property is deprecated, use LayoutUseAsItemLayoutUse instead")]
            #pragma warning disable CS1591
            [QueryParameter("layoutUse")]
            public string? LayoutUse { get; set; } = default!;
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("layoutUse")]
            public global::Bones.Api.Client.AutoGen.Models.ItemLayoutUse? LayoutUseAsItemLayoutUse { get; set; } = default!;
            #pragma warning restore CS1591
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
        public partial class LayoutsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bones.Api.Client.AutoGen.GenericItem.Item.Layouts.LayoutsRequestBuilder.LayoutsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
