// <auto-generated />
using System;
using Bones.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bones.Database.Migrations
{
    [DbContext(typeof(BonesDbContext))]
    [Migration("20240823054817_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BonesRoles", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("BonesRoleClaims", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EmailConfirmedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PasswordExpired")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("BonesUsers", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BonesUserClaims", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("BonesUserLogins", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("BonesUserRoles", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("BonesUserTokens", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwningOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwningUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwningOrganizationId");

                    b.HasIndex("OwningUserId");

                    b.ToTable("Assets", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetLayoutVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetLayoutVersionId");

                    b.ToTable("AssetFields", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetFieldListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MatchingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentFieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentFieldId");

                    b.ToTable("AssetFieldListEntries", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("AssetLayouts", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetLayoutVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetLayoutId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetLayoutId");

                    b.ToTable("AssetLayoutVersions", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssetVersionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetVersionId");

                    b.HasIndex("FieldId");

                    b.ToTable("AssetValues", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetLayoutId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetLayoutId");

                    b.ToTable("AssetVersions", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("BonesOrganizations", "OrganizationManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Initiatives", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedToQueueDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("Items", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ItemLayoutVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemLayoutVersionId");

                    b.ToTable("ItemFields", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemFieldListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MatchingType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParentFieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentFieldId");

                    b.ToTable("ItemFieldListEntries", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("ItemLayouts", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemLayoutVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemLayoutId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemLayoutId");

                    b.ToTable("ItemLayoutVersions", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LocationType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("ItemVersionId");

                    b.ToTable("ItemValues", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemLayoutId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemLayoutId");

                    b.ToTable("ItemVersions", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwningOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwningUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwningOrganizationId");

                    b.HasIndex("OwningUserId");

                    b.ToTable("Projects", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Queue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Queues", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Tags", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRole", b =>
                {
                    b.HasOne("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRoleClaim", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserClaim", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserLogin", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserRole", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserToken", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.Asset", b =>
                {
                    b.HasOne("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", "OwningOrganization")
                        .WithMany("Assets")
                        .HasForeignKey("OwningOrganizationId");

                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", "OwningUser")
                        .WithMany("Assets")
                        .HasForeignKey("OwningUserId");

                    b.Navigation("OwningOrganization");

                    b.Navigation("OwningUser");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetField", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetLayoutVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("AssetLayoutVersionId");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetFieldListEntry", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetField", "ParentField")
                        .WithMany("PossibleValues")
                        .HasForeignKey("ParentFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentField");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetLayoutVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetLayout", "AssetLayout")
                        .WithMany("Versions")
                        .HasForeignKey("AssetLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetLayout");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetValue", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetVersion", null)
                        .WithMany("Values")
                        .HasForeignKey("AssetVersionId");

                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AssetManagement.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.AssetManagement.AssetLayoutVersion", "AssetLayout")
                        .WithMany()
                        .HasForeignKey("AssetLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("AssetLayout");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany("Initiatives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Item", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Queue", "Queue")
                        .WithMany("Items")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemField", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemLayoutVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("ItemLayoutVersionId");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemFieldListEntry", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemField", "ParentField")
                        .WithMany("PossibleValues")
                        .HasForeignKey("ParentFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentField");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemLayoutVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemLayout", "ItemLayout")
                        .WithMany("Versions")
                        .HasForeignKey("ItemLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemLayout");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemValue", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemVersion", null)
                        .WithMany("Values")
                        .HasForeignKey("ItemVersionId");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Item", "Item")
                        .WithMany("Versions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.ProjectManagement.ItemLayoutVersion", "ItemLayout")
                        .WithMany()
                        .HasForeignKey("ItemLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemLayout");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.HasOne("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", "OwningOrganization")
                        .WithMany("Projects")
                        .HasForeignKey("OwningOrganizationId");

                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", "OwningUser")
                        .WithMany("Projects")
                        .HasForeignKey("OwningUserId");

                    b.Navigation("OwningOrganization");

                    b.Navigation("OwningUser");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Queue", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Initiative", "Initiative")
                        .WithMany("Queues")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Tag", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Item", null)
                        .WithMany("Tags")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUser", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetField", b =>
                {
                    b.Navigation("PossibleValues");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetLayout", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetLayoutVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.AssetVersion", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Projects");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Item", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemField", b =>
                {
                    b.Navigation("PossibleValues");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemLayout", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemLayoutVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.ItemVersion", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.Navigation("Initiatives");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Queue", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
