using Bones.Database.DbConsts;
using Bones.Database.DbSets.Organizations;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bones.Database.DbSets.Accounts;

/// <summary>
///   Model for the Accounts.BonesRoles table.
/// </summary>
[Table(TableNames.Accounts.BonesRoles, Schema = SchemaNames.Accounts)]
public class BonesRole : IdentityRole<Guid>
{
    /// <summary>
    ///   Is this a system-level role?
    /// </summary>
    public bool IsSystemRole { get; set; } = false;

    /// <summary>
    ///   If this is an organizational role, which organization does it belong to?
    /// </summary>
    public Guid? OrganizationId { get; set; }

    /// <summary>
    ///   If this role was generated by the system it is managed by the system
    ///   and should not be edited by organization users. They can still add users.
    /// </summary>
    public bool ReadOnlyRole { get; set; } = false;

    #region Navigational Properties
    /// <summary>
    ///   Navigational property for the organization this role belongs to, null if not an organizational role or not .Include()'d in the query
    /// </summary>
    public BonesOrganization? Organization { get; set; }
    #endregion

    /// <summary>
    ///   Needed to override the default table name and schema that <see cref="IdentityRole{Guid}" /> uses.
    ///   Seems the attribute is ignored by that, still keeping it there for consistency though.
    /// </summary>
    /// <param name="builder"></param>
    internal static void BuildTable(EntityTypeBuilder<BonesRole> builder)
    {
        builder.ToTable(TableNames.Accounts.BonesRoles, SchemaNames.Accounts);

        builder.HasOne(r => r.Organization)
               .WithMany(o => o.Roles)
               .HasForeignKey(r => r.OrganizationId);
    }
}