// <auto-generated />
using System;
using System.Collections.Generic;
using Bones.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bones.Database.Migrations
{
    [DbContext(typeof(BonesDbContext))]
    partial class BonesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReadOnlyRole")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("OrganizationId");

                    b.ToTable("BonesRoles", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("BonesRoleClaims", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EmailConfirmedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PasswordExpired")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("BonesUser", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BonesUserClaims", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("BonesUserLogins", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("BonesUserRoles", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("BonesUserTokens", "AccountManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Assets", "AssetManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GenericItemLayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GenericItemLayoutId");

                    b.HasIndex("ProjectId");

                    b.ToTable("GenericItems", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GenericItemFields", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemFieldListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GenericItemFieldVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchingType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GenericItemFieldVersionId");

                    b.ToTable("GenericItemFieldListEntries", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemFieldVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("CanBeNegative")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GenericItemFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GenericItemLayoutVersionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GeoLocationType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("RequiredAddressFields")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GenericItemFieldId");

                    b.HasIndex("GenericItemLayoutVersionId");

                    b.ToTable("GenericItemFieldVersions", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<long>("FriendlyIdNonce")
                        .HasColumnType("bigint");

                    b.Property<string>("FriendlyIdPrefix")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GenericItemLayouts", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayoutVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("EnabledFor")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemLayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemLayoutId");

                    b.ToTable("GenericItemLayoutVersions", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GenericItemVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("GenericItemVersionId");

                    b.HasIndex("LocationId");

                    b.ToTable("GenericItemValues", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("GenericItemLayoutVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GenericItemLayoutVersionId");

                    b.HasIndex("ItemId");

                    b.ToTable("GenericItemVersions", "GenericItem");
                });

            modelBuilder.Entity("Bones.Database.DbSets.MappingManagement.GeoLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityOrPlace")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GeoLocated")
                        .HasColumnType("boolean");

                    b.Property<string>("Geometry")
                        .HasColumnType("text");

                    b.Property<long?>("LastAcknowledgedOsmVersion")
                        .HasColumnType("bigint");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OsmObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StateOrProvince")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OsmObjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("GeoLocations", "MappingManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.MappingManagement.OsmObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<bool>("DeletedOnOsmFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastOsmGeometryUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastOsmVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("OsmGeometry")
                        .HasColumnType("text");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<int>("OsmType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OsmObjects", "MappingManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("BonesOrganizations", "OrganizationManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Initiatives", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwningOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwningUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwningOrganizationId");

                    b.HasIndex("OwningUserId");

                    b.ToTable("Projects", "ProjectManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.System.ConfirmationEmailDeadQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationLink")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("DeadQueueCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("FailureReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("LastTry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OriginalCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationEmailDeadQueue", "System");
                });

            modelBuilder.Entity("Bones.Database.DbSets.System.ConfirmationEmailQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationLink")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("FailureReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("LastTry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConfirmationEmailQueue", "System");
                });

            modelBuilder.Entity("Bones.Database.DbSets.System.ForgotPasswordEmailDeadQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeadQueueCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("FailureReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("LastTry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OriginalCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetLink")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordEmailDeadQueue", "System");
                });

            modelBuilder.Entity("Bones.Database.DbSets.System.ForgotPasswordEmailQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.PrimitiveCollection<List<string>>("FailureReasons")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("LastTry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetLink")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ForgotPasswordEmailQueue", "System");
                });

            modelBuilder.Entity("Bones.Database.DbSets.System.TaskError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("ErrorTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskErrors", "System");
                });

            modelBuilder.Entity("Bones.Database.DbSets.WorkItemManagement.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedToQueueDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkItemQueueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("WorkItemQueueId");

                    b.ToTable("WorkItems", "WorkItemManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.WorkItemManagement.WorkItemQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DeleteFlag")
                        .HasColumnType("boolean");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("WorkItemQueues", "WorkItemManagement");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRole", b =>
                {
                    b.HasOne("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesRoleClaim", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserClaim", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserLogin", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserRole", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUserToken", b =>
                {
                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.AssetManagement.Asset", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItem", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemLayout", "GenericItemLayout")
                        .WithMany()
                        .HasForeignKey("GenericItemLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericItemLayout");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemField", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemFieldListEntry", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemFieldVersion", null)
                        .WithMany("PossibleValues")
                        .HasForeignKey("GenericItemFieldVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemFieldVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemField", "GenericItemField")
                        .WithMany("Versions")
                        .HasForeignKey("GenericItemFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemLayoutVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("GenericItemLayoutVersionId");

                    b.Navigation("GenericItemField");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayout", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayoutVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemLayout", "ItemLayout")
                        .WithMany("Versions")
                        .HasForeignKey("ItemLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemLayout");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemValue", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemFieldVersion", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemVersion", null)
                        .WithMany("Values")
                        .HasForeignKey("GenericItemVersionId");

                    b.HasOne("Bones.Database.DbSets.MappingManagement.GeoLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Field");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemVersion", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItemLayoutVersion", "GenericItemLayoutVersion")
                        .WithMany()
                        .HasForeignKey("GenericItemLayoutVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItem", "Item")
                        .WithMany("Versions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenericItemLayoutVersion");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Bones.Database.DbSets.MappingManagement.GeoLocation", b =>
                {
                    b.HasOne("Bones.Database.DbSets.MappingManagement.OsmObject", "OsmObject")
                        .WithMany()
                        .HasForeignKey("OsmObjectId");

                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OsmObject");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Project", "Project")
                        .WithMany("Initiatives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.HasOne("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", "OwningOrganization")
                        .WithMany("Projects")
                        .HasForeignKey("OwningOrganizationId");

                    b.HasOne("Bones.Database.DbSets.AccountManagement.BonesUser", "OwningUser")
                        .WithMany("Projects")
                        .HasForeignKey("OwningUserId");

                    b.Navigation("OwningOrganization");

                    b.Navigation("OwningUser");
                });

            modelBuilder.Entity("Bones.Database.DbSets.WorkItemManagement.WorkItem", b =>
                {
                    b.HasOne("Bones.Database.DbSets.GenericItems.GenericItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bones.Database.DbSets.WorkItemManagement.WorkItemQueue", "WorkItemQueue")
                        .WithMany("WorkItems")
                        .HasForeignKey("WorkItemQueueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("WorkItemQueue");
                });

            modelBuilder.Entity("Bones.Database.DbSets.WorkItemManagement.WorkItemQueue", b =>
                {
                    b.HasOne("Bones.Database.DbSets.ProjectManagement.Initiative", "Initiative")
                        .WithMany("Queues")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("Bones.Database.DbSets.AccountManagement.BonesUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItem", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemField", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemFieldVersion", b =>
                {
                    b.Navigation("PossibleValues");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayout", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemLayoutVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Bones.Database.DbSets.GenericItems.GenericItemVersion", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Bones.Database.DbSets.OrganizationManagement.BonesOrganization", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Initiative", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("Bones.Database.DbSets.ProjectManagement.Project", b =>
                {
                    b.Navigation("Initiatives");
                });

            modelBuilder.Entity("Bones.Database.DbSets.WorkItemManagement.WorkItemQueue", b =>
                {
                    b.Navigation("WorkItems");
                });
#pragma warning restore 612, 618
        }
    }
}
