using Bones.Database.DbSets.OrganizationManagement;
using Microsoft.AspNetCore.Identity;

namespace Bones.Database.DbSets.AccountManagement;

/// <summary>
///     Model for the AccountManagement.BonesRoles table.
/// </summary>
[Table("BonesRoles", Schema = "AccountManagement")]
public class BonesRole : IdentityRole<Guid>
{
    /// <summary>
    ///   Is this a system-level role?
    /// </summary>
    public bool IsSystemRole { get; set; } = false;

    /// <summary>
    ///   If this is an organizational role, which organization does it belong to?
    /// </summary>
    public BonesOrganization? Organization { get; set; }

    /// <summary>
    ///   If this role was generated by the system it is managed by the system
    ///   and should not be edited by organization users. They can still add users.
    /// </summary>
    public bool ReadOnlyRole { get; set; } = false;
}