// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Asset.ActionNamespace.Create;
using Bones.Api.Client.AutoGen.Asset.ActionNamespace.CreateVersion;
using Bones.Api.Client.AutoGen.Asset.ActionNamespace.Delete;
using Bones.Api.Client.AutoGen.Asset.ActionNamespace.DeleteVersion;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Asset.ActionNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \Asset\action
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class ActionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.Create.CreateRequestBuilder Create
        {
            get => new global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The createVersion property</summary>
        public global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.CreateVersion.CreateVersionRequestBuilder CreateVersion
        {
            get => new global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.CreateVersion.CreateVersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deleteVersion property</summary>
        public global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.DeleteVersion.DeleteVersionRequestBuilder DeleteVersion
        {
            get => new global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.DeleteVersion.DeleteVersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.ActionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Asset/action", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Asset.ActionNamespace.ActionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Asset/action", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
