// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Account;
using Bones.Api.Client.AutoGen.Anonymous;
using Bones.Api.Client.AutoGen.Asset;
using Bones.Api.Client.AutoGen.AssetSearch;
using Bones.Api.Client.AutoGen.Initiative;
using Bones.Api.Client.AutoGen.ItemLayout;
using Bones.Api.Client.AutoGen.ItemVersion;
using Bones.Api.Client.AutoGen.Login;
using Bones.Api.Client.AutoGen.MyAccount;
using Bones.Api.Client.AutoGen.Project;
using Bones.Api.Client.AutoGen.ProjectSearch;
using Bones.Api.Client.AutoGen.SysAdmin;
using Bones.Api.Client.AutoGen.TaskNamespace;
using Bones.Api.Client.AutoGen.TaskQueue;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using ReQuesty.Runtime.Serialization.Form;
using ReQuesty.Runtime.Serialization.Json;
using ReQuesty.Runtime.Serialization.Multipart;
using ReQuesty.Runtime.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class AutoGenBonesApiClient : BaseRequestBuilder
    {
        /// <summary>The Account property</summary>
        public global::Bones.Api.Client.AutoGen.Account.AccountRequestBuilder Account
        {
            get => new global::Bones.Api.Client.AutoGen.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Anonymous property</summary>
        public global::Bones.Api.Client.AutoGen.Anonymous.AnonymousRequestBuilder Anonymous
        {
            get => new global::Bones.Api.Client.AutoGen.Anonymous.AnonymousRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Asset property</summary>
        public global::Bones.Api.Client.AutoGen.Asset.AssetRequestBuilder Asset
        {
            get => new global::Bones.Api.Client.AutoGen.Asset.AssetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The AssetSearch property</summary>
        public global::Bones.Api.Client.AutoGen.AssetSearch.AssetSearchRequestBuilder AssetSearch
        {
            get => new global::Bones.Api.Client.AutoGen.AssetSearch.AssetSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Initiative property</summary>
        public global::Bones.Api.Client.AutoGen.Initiative.InitiativeRequestBuilder Initiative
        {
            get => new global::Bones.Api.Client.AutoGen.Initiative.InitiativeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ItemLayout property</summary>
        public global::Bones.Api.Client.AutoGen.ItemLayout.ItemLayoutRequestBuilder ItemLayout
        {
            get => new global::Bones.Api.Client.AutoGen.ItemLayout.ItemLayoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ItemVersion property</summary>
        public global::Bones.Api.Client.AutoGen.ItemVersion.ItemVersionRequestBuilder ItemVersion
        {
            get => new global::Bones.Api.Client.AutoGen.ItemVersion.ItemVersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Login property</summary>
        public global::Bones.Api.Client.AutoGen.Login.LoginRequestBuilder Login
        {
            get => new global::Bones.Api.Client.AutoGen.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The MyAccount property</summary>
        public global::Bones.Api.Client.AutoGen.MyAccount.MyAccountRequestBuilder MyAccount
        {
            get => new global::Bones.Api.Client.AutoGen.MyAccount.MyAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Project property</summary>
        public global::Bones.Api.Client.AutoGen.Project.ProjectRequestBuilder Project
        {
            get => new global::Bones.Api.Client.AutoGen.Project.ProjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ProjectSearch property</summary>
        public global::Bones.Api.Client.AutoGen.ProjectSearch.ProjectSearchRequestBuilder ProjectSearch
        {
            get => new global::Bones.Api.Client.AutoGen.ProjectSearch.ProjectSearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The SysAdmin property</summary>
        public global::Bones.Api.Client.AutoGen.SysAdmin.SysAdminRequestBuilder SysAdmin
        {
            get => new global::Bones.Api.Client.AutoGen.SysAdmin.SysAdminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The Task property</summary>
        public global::Bones.Api.Client.AutoGen.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::Bones.Api.Client.AutoGen.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The TaskQueue property</summary>
        public global::Bones.Api.Client.AutoGen.TaskQueue.TaskQueueRequestBuilder TaskQueue
        {
            get => new global::Bones.Api.Client.AutoGen.TaskQueue.TaskQueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.AutoGenBonesApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoGenBonesApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#nullable restore
#pragma warning restore CS0618
