// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Project.Projects.ByOwner;
using Bones.Api.Client.AutoGen.Project.Projects.QuickSelect;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Project.Projects
{
    /// <summary>
    /// Builds and executes requests for operations under \Project\projects
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class ProjectsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The byOwner property</summary>
        public global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerRequestBuilder ByOwner
        {
            get => new global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The quickSelect property</summary>
        public global::Bones.Api.Client.AutoGen.Project.Projects.QuickSelect.QuickSelectRequestBuilder QuickSelect
        {
            get => new global::Bones.Api.Client.AutoGen.Project.Projects.QuickSelect.QuickSelectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Project.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Project/projects", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Project.Projects.ProjectsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProjectsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Project/projects", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
