// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Project.Projects.ByOwner
{
    [Obsolete("This class is obsolete. Use ByOwnerGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    #pragma warning disable CS1591
    public partial class ByOwnerResponse : global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Project.Projects.ByOwner.ByOwnerResponse();
        }
    }
}
#nullable restore
#pragma warning restore CS0618
