// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Assignment.Asset.Item.Latest;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Assignment.Asset.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Assignment\asset\{assetId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class WithAssetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::Bones.Api.Client.AutoGen.Assignment.Asset.Item.Latest.LatestRequestBuilder Latest
        {
            get => new global::Bones.Api.Client.AutoGen.Assignment.Asset.Item.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Assignment.Asset.Item.WithAssetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAssetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Assignment/asset/{assetId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Assignment.Asset.Item.WithAssetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAssetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Assignment/asset/{assetId}", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
