// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Item_Escaped.Fields.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Item_Escaped.Fields
{
    /// <summary>
    /// Builds and executes requests for operations under \Item\fields
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class FieldsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.Item_Escaped.fields.item collection</summary>
        /// <param name="position">The ID of the field</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Fields.Item.WithFieldItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.Item_Escaped.Fields.Item.WithFieldItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("fieldId", position);
                return new global::Bones.Api.Client.AutoGen.Item_Escaped.Fields.Item.WithFieldItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Item/fields", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Fields.FieldsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FieldsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Item/fields", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
