// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Project.Item.Initiative.Create;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Project.Item.Initiative
{
    /// <summary>
    /// Builds and executes requests for operations under \Project\{projectId}\initiative
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class InitiativeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Bones.Api.Client.AutoGen.Project.Item.Initiative.Create.CreateRequestBuilder Create
        {
            get => new global::Bones.Api.Client.AutoGen.Project.Item.Initiative.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Project.Item.Initiative.InitiativeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InitiativeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Project/{projectId}/initiative", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Project.Item.Initiative.InitiativeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InitiativeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Project/{projectId}/initiative", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
