// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Item_Escaped.Layouts.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Item_Escaped.Layouts
{
    /// <summary>
    /// Builds and executes requests for operations under \Item\layouts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class LayoutsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.Item_Escaped.layouts.item collection</summary>
        /// <param name="position">The ID of the layout</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Layouts.Item.WithLayoutItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.Item_Escaped.Layouts.Item.WithLayoutItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("layoutId", position);
                return new global::Bones.Api.Client.AutoGen.Item_Escaped.Layouts.Item.WithLayoutItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Item/layouts", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Item_Escaped.Layouts.LayoutsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LayoutsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Item/layouts", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
