namespace Bones.Database.Operations.AccountManagement.SetEmailConfirmedDateTimeDb;

internal sealed class SetEmailConfirmedDateTimeDbCommandValidator : AbstractValidator<SetEmailConfirmedDateTimeDbCommand>
{

}