// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign
{
    /// <summary>
    /// Builds and executes requests for operations under \Task\action\unassign
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class UnassignRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign.UnassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnassignRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Task/action/unassign", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign.UnassignRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UnassignRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Task/action/unassign", rawUrl)
        {
        }
        /// <summary>
        /// Unassigns a
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.TaskActionResponse"/></returns>
        /// <param name="body">Action to unassign a  from a user.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::Bones.Api.Client.AutoGen.Models.TaskActionResponse?> PostAsync(global::Bones.Api.Client.AutoGen.Models.UnassignTaskAction body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Bones.Api.Client.AutoGen.Models.TaskActionResponse>(requestInfo, global::Bones.Api.Client.AutoGen.Models.TaskActionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Unassigns a
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Action to unassign a  from a user.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPostRequestInformation(global::Bones.Api.Client.AutoGen.Models.UnassignTaskAction body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign.UnassignRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign.UnassignRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bones.Api.Client.AutoGen.TaskNamespace.ActionNamespace.Unassign.UnassignRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
