// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Assignment.Asset;
using Bones.Api.Client.AutoGen.Assignment.TaskNamespace;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Assignment
{
    /// <summary>
    /// Builds and executes requests for operations under \Assignment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class AssignmentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The asset property</summary>
        public global::Bones.Api.Client.AutoGen.Assignment.Asset.AssetRequestBuilder Asset
        {
            get => new global::Bones.Api.Client.AutoGen.Assignment.Asset.AssetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::Bones.Api.Client.AutoGen.Assignment.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::Bones.Api.Client.AutoGen.Assignment.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Assignment.AssignmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignmentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Assignment", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Assignment.AssignmentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssignmentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Assignment", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
