// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bones.Api.Client.AutoGen.Account.My.Session
{
    /// <summary>
    /// Builds and executes requests for operations under \Account\my\session
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class SessionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/my/session{?sessionId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SessionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/my/session{?sessionId*}", rawUrl)
        {
        }
        /// <summary>
        /// Gets or creates a session token for the user and an encryption key to be used for the session.All data stored in localStorage on the client side should be encrypted with the encryption key, to protect against XSS attacks.This encryption key should not be persistantly saved in the client, instead save the session token Guid and use it to retrieve the encryption key from the server.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse?> GetAsync(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder.SessionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse>(requestInfo, global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets or creates a session token for the user and an encryption key to be used for the session.All data stored in localStorage on the client side should be encrypted with the encryption key, to protect against XSS attacks.This encryption key should not be persistantly saved in the client, instead save the session token Guid and use it to retrieve the encryption key from the server.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder.SessionRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets or creates a session token for the user and an encryption key to be used for the session.All data stored in localStorage on the client side should be encrypted with the encryption key, to protect against XSS attacks.This encryption key should not be persistantly saved in the client, instead save the session token Guid and use it to retrieve the encryption key from the server.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
        public partial class SessionRequestBuilderGetQueryParameters 
        {
            /// <summary>The session token to use, if null a new one will be created</summary>
            [QueryParameter("sessionId")]
            public string? SessionId { get; set; } = default!;
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
        public partial class SessionRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Bones.Api.Client.AutoGen.Account.My.Session.SessionRequestBuilder.SessionRequestBuilderGetQueryParameters>
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
