// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Initiative.Item.Dashboard;
using Bones.Api.Client.AutoGen.Initiative.Item.TaskQueues;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Initiative.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Initiative\{initiativeId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class WithInitiativeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dashboard property</summary>
        public global::Bones.Api.Client.AutoGen.Initiative.Item.Dashboard.DashboardRequestBuilder Dashboard
        {
            get => new global::Bones.Api.Client.AutoGen.Initiative.Item.Dashboard.DashboardRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taskQueues property</summary>
        public global::Bones.Api.Client.AutoGen.Initiative.Item.TaskQueues.TaskQueuesRequestBuilder TaskQueues
        {
            get => new global::Bones.Api.Client.AutoGen.Initiative.Item.TaskQueues.TaskQueuesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Initiative.Item.WithInitiativeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInitiativeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Initiative/{initiativeId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Initiative.Item.WithInitiativeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithInitiativeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Initiative/{initiativeId}", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
