using System.Text.Json;
using System.Text.Json.Serialization;

namespace Bones.Api.Client;

/// <summary>
///   The client for the Bones API.
/// </summary>
public class BonesApiClient : AutoGenBonesApiClient
{
    /// <summary>
    ///   Create an instance with a preconfigured <see cref="HttpClient"/>.
    /// </summary>
    /// <param name="httpClient"></param>
    public BonesApiClient(HttpClient httpClient) : base(httpClient) { }

    /// <summary>
    ///   Create an instance with a preconfigured <see cref="HttpClient"/> from the <see cref="IHttpClientFactory"/>
    /// </summary>
    /// <param name="httpClientFactory"></param>
    public BonesApiClient(IHttpClientFactory httpClientFactory) : base(httpClientFactory.CreateClient(HTTP_CLIENT_NAME)) { }

    /// <summary>
    ///   The name of the client as registered in the IHttpClientFactory
    /// </summary>
    public const string HTTP_CLIENT_NAME = "BonesApiClient";
}

/// <summary>
///   Partials for the autogenerated client
/// </summary>
public partial class AutoGenBonesApiClient
{
    static partial void UpdateJsonSerializerSettings(JsonSerializerOptions settings)
    {
        settings.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        settings.WriteIndented = true;
        settings.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
        settings.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
        settings.AllowTrailingCommas = true;
        settings.RespectNullableAnnotations = true;
    }
}