<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <IsPublishable>false</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\Services\Bones.Api\Bones.Api.csproj" />
        <ProjectReference Include="..\..\..\Core\Bones.Database\Bones.Database.csproj" />
        <ProjectReference Include="..\..\..\Core\Bones.Shared.Backend\Bones.Shared.Backend.csproj" />
        <ProjectReference Include="..\..\Bones.Testing.Shared\Bones.Testing.Shared.csproj" />
    </ItemGroup>

</Project>
