<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <!-- install the systemd service when installing the deb/rpm -->
    <PropertyGroup Condition="$(Configuration) == 'Release'">
        <InstallService>true</InstallService>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Core/Bones.Logic/Bones.Logic.csproj" />
        <ProjectReference Include="../../Core/Bones.Shared.Backend/Bones.Shared.Backend.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(Configuration) == 'Release'">
        <Content Remove="appsettings.Development.json" />
        <Content Include="bones-backgroundservice.service" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="1755">
            <LinuxPath>/etc/systemd/system/bones-backgroundservice.service</LinuxPath>
        </Content>
    </ItemGroup>
</Project>
