<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <!-- Build info -->
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <OutputType>Exe</OutputType>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        
        <!-- Assembly info -->
        <VersionPrefix>0.0.1</VersionPrefix>
        <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
        <Authors>Nickolas Gupton</Authors>
        <RepositoryUrl>https://github.com/CorruptComputer/Bones</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
        <SourceRevisionId>develop</SourceRevisionId>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <!-- install the systemd service when installing the deb/rpm -->
    <PropertyGroup Condition="$(Configuration) == 'Release'">
        <InstallService>true</InstallService>
    </PropertyGroup>

    <!-- If building in release mode, replace the SourceRevisionId with the 8 character git commit hash -->
    <Target Condition="$(Configuration) == 'Release'" Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
        <Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8"
              ConsoleToMSBuild="True" IgnoreExitCode="False">
            <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput"/>
        </Exec>
    </Target>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="System.Private.Uri" Version="4.3.2" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
        <PackageReference Update="Packaging.Targets">
            <Version>0.1.232</Version>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Bones.Logic\Bones.Logic.csproj" />
        <ProjectReference Include="..\..\Core\Bones.Shared.Backend\Bones.Shared.Backend.csproj" />
    </ItemGroup>

    <ItemGroup Condition="$(Configuration) == 'Release'">
        <Content Remove="appsettings.Development.json" />
        <Content Include="bones-backgroundservice.service" CopyToPublishDirectory="PreserveNewest" LinuxFileMode="1755">
            <LinuxPath>/etc/systemd/system/bones-backgroundservice.service</LinuxPath>
        </Content>
    </ItemGroup>
</Project>
