// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Account.Item;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Account
{
    /// <summary>
    /// Builds and executes requests for operations under \Account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class AccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.Account.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Account.Item.WithBonesUserItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.Account.Item.WithBonesUserItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("bonesUserId", position);
                return new global::Bones.Api.Client.AutoGen.Account.Item.WithBonesUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.AccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
