name: setup-env
description: Setup Environment

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Print .NET version and SDKs
      shell: bash
      run: |
        dotnet --version
        dotnet --list-sdks

    - name: Restore Tools
      shell: bash
      run: |
        cd Services/Bones.Api
        dotnet tool restore
        cd ../..
        cd Services/Bones.BackgroundService
        dotnet tool restore
        cd ../..
        cd Frontend/Bones.Api.Client
        dotnet tool restore
        cd ../..
        cd Frontend/Bones.WebUI
        dotnet workload restore
        cd ../..