name: setup-env
description: Setup Environment

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install Tools
      shell: bash
      run: |
        sudo apt-get install -y rpm
        dotnet tool install --global shipyard
        cd Services/Bones.Api
        dotnet tool restore
        cd ../..
        cd Frontend/Bones.WebUI
        dotnet workload restore
        cd ../..

    - name: Print .NET version and SDKs
      shell: bash
      run: |
        dotnet --version
        dotnet --list-sdks
