namespace Bones.Backend.Features.AccountManagement.QueueResendConfirmationEmail;

internal class QueueResendConfirmationEmailCommandValidator : AbstractValidator<QueueResendConfirmationEmailCommand>
{

}