<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <TargetFramework>net8.0</TargetFramework>
        <VersionPrefix>0.0.1</VersionPrefix>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration) == 'Release'">
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration) == 'Debug'">
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
        <PackageReference Update="Packaging.Targets">
          <Version>0.1.226</Version>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Bones.Backend\Bones.Backend.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="appsettings.Development.json" Condition="$(Configuration) == 'Release'" />
    </ItemGroup>
</Project>
