<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <!-- Aspire -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.5.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.2" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />

        <!-- Everything else -->
        <PackageReference Include="Autofac" Version="9.1.0" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Questy" Version="0.0.9" />
        <PackageReference Include="Questy.Autofac" Version="0.0.8" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Bones.Shared/Bones.Shared.csproj" />
    </ItemGroup>
</Project>
