<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!-- Build info -->
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        
        <!-- Assembly info -->
        <VersionPrefix>0.0.1</VersionPrefix>
        <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
        <Authors>Nickolas Gupton</Authors>
        <RepositoryUrl>https://github.com/CorruptComputer/Bones</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
        <SourceRevisionId>develop</SourceRevisionId>

        <!-- Aspire -->
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <!-- This seems like it could be useful -->
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <!-- If building in release mode, replace the SourceRevisionId with the 8 character git commit hash -->
    <Target Condition="$(Configuration) == 'Release'" Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
        <Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8"
              ConsoleToMSBuild="True" IgnoreExitCode="False">
            <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput"/>
        </Exec>
    </Target>
    
    <ItemGroup>
        <!-- Aspire -->
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.4.0" />
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="9.1.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
        
        <!-- Everything else -->
        <PackageReference Include="Autofac" Version="8.2.1" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="FluentValidation" Version="11.11.0" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
        <PackageReference Include="GeoJSON.Text" Version="1.1.0" />
        <PackageReference Include="MediatR" Version="12.5.0" />
        <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="12.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Bones.Shared\Bones.Shared.csproj" />
    </ItemGroup>

</Project>
