<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
        <PackageReference Include="ReQuesty.Runtime" Version="0.0.7" />
    </ItemGroup>

    <Target Name="GenerateApiClient" AfterTargets="BeforeBuild" Condition="$(Configuration) == 'Debug'">
        <Message Text="Installing ReQuesty" Importance="High" />
        <Exec Command="dotnet tool install requesty --allow-downgrade --version 0.0.2" />

        <Message Text="Generating API Client" Importance="High" />
        <Exec Command="dotnet tool run requesty generate --openapi ../../../Bones/Services/Bones.Api/OpenApi/swagger.json --output ./AutoGen --class-name AutoGenBonesApiClient --namespace-name Bones.Api.Client.AutoGen --clean-output" />
    </Target>

    <ItemGroup>
      <ProjectReference Include="../../Core/Bones.Shared/Bones.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="nswag.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
    </ItemGroup>

</Project>
