// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.MyAccount.Email;
using Bones.Api.Client.AutoGen.MyAccount.Password;
using Bones.Api.Client.AutoGen.MyAccount.Profile;
using Bones.Api.Client.AutoGen.MyAccount.Session;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.MyAccount
{
    /// <summary>
    /// Builds and executes requests for operations under \MyAccount
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class MyAccountRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The email property</summary>
        public global::Bones.Api.Client.AutoGen.MyAccount.Email.EmailRequestBuilder Email
        {
            get => new global::Bones.Api.Client.AutoGen.MyAccount.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The password property</summary>
        public global::Bones.Api.Client.AutoGen.MyAccount.Password.PasswordRequestBuilder Password
        {
            get => new global::Bones.Api.Client.AutoGen.MyAccount.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::Bones.Api.Client.AutoGen.MyAccount.Profile.ProfileRequestBuilder Profile
        {
            get => new global::Bones.Api.Client.AutoGen.MyAccount.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The session property</summary>
        public global::Bones.Api.Client.AutoGen.MyAccount.Session.SessionRequestBuilder Session
        {
            get => new global::Bones.Api.Client.AutoGen.MyAccount.Session.SessionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.MyAccount.MyAccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyAccountRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MyAccount", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.MyAccount.MyAccountRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MyAccountRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/MyAccount", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
