// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response to the GetWebConfigAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class ApiConfigResponse : IParsable
    {
        /// <summary>The version for the API</summary>
        public string ApiVersion { get; set; } = default!;
        /// <summary>When was this config requested</summary>
        public DateTimeOffset RequestedAt { get; set; } = default!;
        /// <summary>Is the API setup for testing?</summary>
        public bool SetupForTesting { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.ApiConfigResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.ApiConfigResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.ApiConfigResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiVersion", n => { ApiVersion = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ApiVersion'"); } },
                { "requestedAt", n => { RequestedAt = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'RequestedAt'"); } },
                { "setupForTesting", n => { SetupForTesting = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'SetupForTesting'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiVersion", ApiVersion);
            writer.WriteDateTimeOffsetValue("requestedAt", RequestedAt);
            writer.WriteBoolValue("setupForTesting", SetupForTesting);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
