// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Model representing an assignment slot for an item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class AssignmentSlotModel : IParsable
    {
        /// <summary>The unique identifier for the assignment slot.</summary>
        public Guid AssignmentSlotId { get; set; } = default!;
        /// <summary>The assignmentSlotLevel property</summary>
        public global::Bones.Api.Client.AutoGen.Models.AssignmentType? AssignmentSlotLevel { get; set; } = default!;
        /// <summary>The name of the assignment slot.</summary>
        public string AssignmentSlotName { get; set; } = default!;
        /// <summary>The states in which this assignment can be</summary>
        public List<string> AssignmentStates { get; set; } = default!;
        /// <summary>The display order for this assignee slot</summary>
        public int OrderIndex { get; set; } = default!;
        /// <summary>The selectionSlotType property</summary>
        public global::Bones.Api.Client.AutoGen.Models.SelectionType? SelectionSlotType { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.AssignmentSlotModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.AssignmentSlotModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.AssignmentSlotModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assignmentSlotId", n => { AssignmentSlotId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AssignmentSlotId'"); } },
                { "assignmentSlotLevel", n => { AssignmentSlotLevel = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.AssignmentType>(); } },
                { "assignmentSlotName", n => { AssignmentSlotName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AssignmentSlotName'"); } },
                { "assignmentStates", n => { AssignmentStates = n.GetCollectionOfPrimitiveValues<string>()?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AssignmentStates'"); } },
                { "orderIndex", n => { OrderIndex = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'OrderIndex'"); } },
                { "selectionSlotType", n => { SelectionSlotType = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.SelectionType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("assignmentSlotId", AssignmentSlotId);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.AssignmentType>("assignmentSlotLevel", AssignmentSlotLevel);
            writer.WriteStringValue("assignmentSlotName", AssignmentSlotName);
            writer.WriteCollectionOfPrimitiveValues<string>("assignmentStates", AssignmentStates);
            writer.WriteIntValue("orderIndex", OrderIndex);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.SelectionType>("selectionSlotType", SelectionSlotType);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
