// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Action to create a new version of a work item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class CreateWorkItemVersionAction : global::Bones.Api.Client.AutoGen.Models.WorkItemActionBase, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The fields of the work item</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.ItemValueModel> FieldValues { get; set; } = default!;
        /// <summary>The title of the work item</summary>
        public string? Title { get; set; } = default!;
        /// <summary>The ID of the work item to perform the action on</summary>
        public Guid? WorkItemId { get; set; } = default!;
        /// <summary>The ID of the work item layout (not version, automatically uses the current version)</summary>
        public Guid? WorkItemLayoutId { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.CreateWorkItemVersionAction"/> and sets the default values.
        /// </summary>
        public CreateWorkItemVersionAction() : base()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.CreateWorkItemVersionAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Bones.Api.Client.AutoGen.Models.CreateWorkItemVersionAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.CreateWorkItemVersionAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "fieldValues", n => { FieldValues = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.ItemValueModel>(global::Bones.Api.Client.AutoGen.Models.ItemValueModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'FieldValues'"); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "workItemId", n => { WorkItemId = n.GetGuidValue(); } },
                { "workItemLayoutId", n => { WorkItemLayoutId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.ItemValueModel>("fieldValues", FieldValues);
            writer.WriteStringValue("title", Title);
            writer.WriteGuidValue("workItemId", WorkItemId);
            writer.WriteGuidValue("workItemLayoutId", WorkItemLayoutId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
