// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Request to create a new project
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class CreateProjectRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>Name of the project to create</summary>
        public string Name { get; set; } = default!;
        /// <summary>Optionally the organization that this should be created under, if not specified will be created for the requesting user.</summary>
        public Guid? OrganizationId { get; set; } = default!;
        /// <summary>The preset to use for this project, if any</summary>
        public global::Bones.Api.Client.AutoGen.Models.ProjectPreset? Preset { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.CreateProjectRequest"/> and sets the default values.
        /// </summary>
        public CreateProjectRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.CreateProjectRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.CreateProjectRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.CreateProjectRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "organizationId", n => { OrganizationId = n.GetGuidValue(); } },
                { "preset", n => { Preset = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.ProjectPreset>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteStringValue("name", Name);
            writer.WriteGuidValue("organizationId", OrganizationId);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.ProjectPreset>("preset", Preset);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
