// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Model for a Task in the dashboard
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class DashboardTaskModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>The date and time the Task was added to the queue</summary>
        public DateTimeOffset AddedToQueueDateTime { get; set; } = default!;
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The friendly ID of the Task</summary>
        public string FriendlyId { get; set; } = default!;
        /// <summary>The ID of the Task</summary>
        public Guid Id { get; set; } = default!;
        /// <summary>The title of the Task</summary>
        public string Title { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel"/> and sets the default values.
        /// </summary>
        public DashboardTaskModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addedToQueueDateTime", n => { AddedToQueueDateTime = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AddedToQueueDateTime'"); } },
                { "friendlyId", n => { FriendlyId = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'FriendlyId'"); } },
                { "id", n => { Id = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Id'"); } },
                { "title", n => { Title = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Title'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteDateTimeOffsetValue("addedToQueueDateTime", AddedToQueueDateTime);
            writer.WriteStringValue("friendlyId", FriendlyId);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
