// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Action to delete a specific version of a work item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class DeleteWorkItemVersionAction : global::Bones.Api.Client.AutoGen.Models.WorkItemActionBase, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The ID of the work item to perform the action on</summary>
        public Guid? WorkItemId { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.DeleteWorkItemVersionAction"/> and sets the default values.
        /// </summary>
        public DeleteWorkItemVersionAction() : base()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.DeleteWorkItemVersionAction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Bones.Api.Client.AutoGen.Models.DeleteWorkItemVersionAction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.DeleteWorkItemVersionAction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "workItemId", n => { WorkItemId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteGuidValue("workItemId", WorkItemId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
