// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// The response body is empty, this is a workaround for the limitations of the API client.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class ErrorResponse : ApiException, IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The error message, if any.</summary>
        public string? ErrorMessage { get; set; } = default!;
        /// <summary>The errors that occurred, with the key being either the input that was invalid and the list of reasons it was invalid, or &apos;server&apos; with the list of server errors.</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.KeyValuePairOfstringAndListOfstring> Errors { get; set; } = default!;
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse"/> and sets the default values.
        /// </summary>
        public ErrorResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.ErrorResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.ErrorResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.KeyValuePairOfstringAndListOfstring>(global::Bones.Api.Client.AutoGen.Models.KeyValuePairOfstringAndListOfstring.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Errors'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.KeyValuePairOfstringAndListOfstring>("errors", Errors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
