// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetAssetLayoutDashboardAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class GetAssetLayoutDashboardResponse : IParsable
    {
        /// <summary>The assets in this layout, ordered by date added from oldest to newest</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.DashboardAssetModel> Assets { get; set; } = default!;
        /// <summary>The name of the layout</summary>
        public string LayoutName { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetAssetLayoutDashboardResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetAssetLayoutDashboardResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetAssetLayoutDashboardResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assets", n => { Assets = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.DashboardAssetModel>(global::Bones.Api.Client.AutoGen.Models.DashboardAssetModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Assets'"); } },
                { "layoutName", n => { LayoutName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'LayoutName'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.DashboardAssetModel>("assets", Assets);
            writer.WriteStringValue("layoutName", LayoutName);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
