// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// API response for the GetLatestItemLayoutVersionAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class GetItemLayoutVersionResponse : IParsable
    {
        /// <summary>The assignee slots for the layout version</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.ItemAssigneeSlotModel> AssigneeSlots { get; set; } = default!;
        /// <summary>The field versions</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.Int32GuidKeyValuePair> FieldVersions { get; set; } = default!;
        /// <summary>The prefix at the start of a Friendly ID for items using this layout, up to 6 letters.</summary>
        public string FriendlyIdPrefix { get; set; } = default!;
        /// <summary>The current latest version of this layout</summary>
        public long LatestVersion { get; set; } = default!;
        /// <summary>The layoutUse property</summary>
        public global::Bones.Api.Client.AutoGen.Models.ItemLayoutUse? LayoutUse { get; set; } = default!;
        /// <summary>Name of the item layout</summary>
        public string Name { get; set; } = default!;
        /// <summary>The ID of the project this layout belongs to</summary>
        public Guid ProjectId { get; set; } = default!;
        /// <summary>The version number for this ItemLayoutVersion</summary>
        public long Version { get; set; } = default!;
        /// <summary>Is there a version update available for this layout version?</summary>
        public bool VersionUpdateAvailable { get; private set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetItemLayoutVersionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetItemLayoutVersionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetItemLayoutVersionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assigneeSlots", n => { AssigneeSlots = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.ItemAssigneeSlotModel>(global::Bones.Api.Client.AutoGen.Models.ItemAssigneeSlotModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AssigneeSlots'"); } },
                { "fieldVersions", n => { FieldVersions = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.Int32GuidKeyValuePair>(global::Bones.Api.Client.AutoGen.Models.Int32GuidKeyValuePair.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'FieldVersions'"); } },
                { "friendlyIdPrefix", n => { FriendlyIdPrefix = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'FriendlyIdPrefix'"); } },
                { "latestVersion", n => { LatestVersion = n.GetLongValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'LatestVersion'"); } },
                { "layoutUse", n => { LayoutUse = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.ItemLayoutUse>(); } },
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "projectId", n => { ProjectId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ProjectId'"); } },
                { "version", n => { Version = n.GetLongValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Version'"); } },
                { "versionUpdateAvailable", n => { VersionUpdateAvailable = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'VersionUpdateAvailable'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.ItemAssigneeSlotModel>("assigneeSlots", AssigneeSlots);
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.Int32GuidKeyValuePair>("fieldVersions", FieldVersions);
            writer.WriteStringValue("friendlyIdPrefix", FriendlyIdPrefix);
            writer.WriteLongValue("latestVersion", LatestVersion);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.ItemLayoutUse>("layoutUse", LayoutUse);
            writer.WriteStringValue("name", Name);
            writer.WriteGuidValue("projectId", ProjectId);
            writer.WriteLongValue("version", Version);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
