// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetMyProfileAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class GetMyProfileResponse : IParsable
    {
        /// <summary>A list of audits that have been performed on the account</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel> AccountAudits { get; set; } = default!;
        /// <summary>The date and time the user was created</summary>
        public DateTimeOffset CreateDateTime { get; set; } = default!;
        /// <summary>The display name of the user, defaults to their email if they don&apos;t have one set</summary>
        public string DisplayName { get; set; } = default!;
        /// <summary>The email address of the user</summary>
        public string Email { get; set; } = default!;
        /// <summary>Have they confirmed their email address?</summary>
        public bool EmailConfirmed { get; set; } = default!;
        /// <summary>If they have confirmed their email address, when they did it</summary>
        public DateTimeOffset? EmailConfirmedDateTime { get; set; } = default!;
        /// <summary>Is the user a system administrator?</summary>
        public bool IsSysAdmin { get; set; } = default!;
        /// <summary>The date and time the user last set their password</summary>
        public DateTimeOffset PasswordLastSetDateTime { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetMyProfileResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetMyProfileResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetMyProfileResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountAudits", n => { AccountAudits = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel>(global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AccountAudits'"); } },
                { "createDateTime", n => { CreateDateTime = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'CreateDateTime'"); } },
                { "displayName", n => { DisplayName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'DisplayName'"); } },
                { "email", n => { Email = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Email'"); } },
                { "emailConfirmed", n => { EmailConfirmed = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'EmailConfirmed'"); } },
                { "emailConfirmedDateTime", n => { EmailConfirmedDateTime = n.GetDateTimeOffsetValue(); } },
                { "isSysAdmin", n => { IsSysAdmin = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'IsSysAdmin'"); } },
                { "passwordLastSetDateTime", n => { PasswordLastSetDateTime = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'PasswordLastSetDateTime'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel>("accountAudits", AccountAudits);
            writer.WriteDateTimeOffsetValue("createDateTime", CreateDateTime);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("emailConfirmed", EmailConfirmed);
            writer.WriteDateTimeOffsetValue("emailConfirmedDateTime", EmailConfirmedDateTime);
            writer.WriteBoolValue("isSysAdmin", IsSysAdmin);
            writer.WriteDateTimeOffsetValue("passwordLastSetDateTime", PasswordLastSetDateTime);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
