// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetOrCreateMySessionAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class GetOrCreateMySessionResponse : IParsable
    {
        /// <summary>The encryption key to use</summary>
        public string Base64LocalStorageKey { get; set; } = default!;
        /// <summary>The session SessionId to use</summary>
        public Guid SessionId { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetOrCreateMySessionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "base64LocalStorageKey", n => { Base64LocalStorageKey = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Base64LocalStorageKey'"); } },
                { "sessionId", n => { SessionId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'SessionId'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("base64LocalStorageKey", Base64LocalStorageKey);
            writer.WriteGuidValue("sessionId", SessionId);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
