// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetProjectDashboardAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class GetProjectDashboardResponse : IParsable
    {
        /// <summary>The types of assets in the project</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.AssetTypesListModel> AssetTypes { get; set; } = default!;
        /// <summary>The number of initiatives in the project</summary>
        public int InitiativeCount { get; set; } = default!;
        /// <summary>A list of the initiatives in the project</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.InitiativeListModel> Initiatives { get; set; } = default!;
        /// <summary>The projects ID</summary>
        public Guid ProjectId { get; set; } = default!;
        /// <summary>The name of the project</summary>
        public string ProjectName { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetProjectDashboardResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetProjectDashboardResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetProjectDashboardResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assetTypes", n => { AssetTypes = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.AssetTypesListModel>(global::Bones.Api.Client.AutoGen.Models.AssetTypesListModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'AssetTypes'"); } },
                { "initiativeCount", n => { InitiativeCount = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'InitiativeCount'"); } },
                { "initiatives", n => { Initiatives = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.InitiativeListModel>(global::Bones.Api.Client.AutoGen.Models.InitiativeListModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Initiatives'"); } },
                { "projectId", n => { ProjectId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ProjectId'"); } },
                { "projectName", n => { ProjectName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ProjectName'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.AssetTypesListModel>("assetTypes", AssetTypes);
            writer.WriteIntValue("initiativeCount", InitiativeCount);
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.InitiativeListModel>("initiatives", Initiatives);
            writer.WriteGuidValue("projectId", ProjectId);
            writer.WriteStringValue("projectName", ProjectName);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
