// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetPublicProfileAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class GetPublicProfileResponse : IParsable
    {
        /// <summary>The ID of the user</summary>
        public Guid BonesUserId { get; set; } = default!;
        /// <summary>The date and time the user was created</summary>
        public DateTimeOffset CreateDateTime { get; set; } = default!;
        /// <summary>The display name of the user, defaults to their email if they don&apos;t have one set</summary>
        public string DisplayName { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetPublicProfileResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetPublicProfileResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetPublicProfileResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bonesUserId", n => { BonesUserId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'BonesUserId'"); } },
                { "createDateTime", n => { CreateDateTime = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'CreateDateTime'"); } },
                { "displayName", n => { DisplayName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'DisplayName'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("bonesUserId", BonesUserId);
            writer.WriteDateTimeOffsetValue("createDateTime", CreateDateTime);
            writer.WriteStringValue("displayName", DisplayName);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
