// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetTaskQueueByIdAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class GetTaskQueueByIdResponse : IParsable
    {
        /// <summary>The ID of the initiative this queue belongs to</summary>
        public Guid InitiativeId { get; set; } = default!;
        /// <summary>The ID of the project this queue belongs to</summary>
        public Guid ProjectId { get; set; } = default!;
        /// <summary>The name of the queue</summary>
        public string QueueName { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetTaskQueueByIdResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetTaskQueueByIdResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetTaskQueueByIdResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "initiativeId", n => { InitiativeId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'InitiativeId'"); } },
                { "projectId", n => { ProjectId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ProjectId'"); } },
                { "queueName", n => { QueueName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'QueueName'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("initiativeId", InitiativeId);
            writer.WriteGuidValue("projectId", ProjectId);
            writer.WriteStringValue("queueName", QueueName);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
