// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Response for the GetTaskQueueDashboardAsync endpoint
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class GetTaskQueueDashboardResponse : IParsable
    {
        /// <summary>The name of the queue</summary>
        public string QueueName { get; set; } = default!;
        /// <summary>The tasks in this queue, ordered by date added from oldest to newest</summary>
        public List<global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel> Tasks { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.GetTaskQueueDashboardResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.GetTaskQueueDashboardResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.GetTaskQueueDashboardResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "queueName", n => { QueueName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'QueueName'"); } },
                { "tasks", n => { Tasks = n.GetCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel>(global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel.CreateFromDiscriminatorValue)?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Tasks'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("queueName", QueueName);
            writer.WriteCollectionOfObjectValues<global::Bones.Api.Client.AutoGen.Models.DashboardTaskModel>("tasks", Tasks);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
