// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Model for the values of an item
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class ItemValueDisplayModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>If the field is a number, can it be negative?</summary>
        public bool? CanBeNegative { get; set; } = default!;
        /// <summary>The ID of the field version this value is for</summary>
        public Guid FieldVersionId { get; set; } = default!;
        /// <summary>Is this field required?</summary>
        public bool IsRequired { get; set; } = default!;
        /// <summary>The name of the field</summary>
        public string Name { get; set; } = default!;
        /// <summary>The order that this field should be displayed in</summary>
        public int OrderNumber { get; set; } = default!;
        /// <summary>If this field is a value list, the possible values for the field</summary>
        public List<string> PossibleValues { get; set; } = default!;
        /// <summary>The value of the field</summary>
        public string? Value { get; set; } = default!;
        /// <summary>The type of the field</summary>
        public global::Bones.Api.Client.AutoGen.Models.FieldType? ValueType { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.ItemValueDisplayModel"/> and sets the default values.
        /// </summary>
        public ItemValueDisplayModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.ItemValueDisplayModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.ItemValueDisplayModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.ItemValueDisplayModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canBeNegative", n => { CanBeNegative = n.GetBoolValue(); } },
                { "fieldVersionId", n => { FieldVersionId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'FieldVersionId'"); } },
                { "isRequired", n => { IsRequired = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'IsRequired'"); } },
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "orderNumber", n => { OrderNumber = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'OrderNumber'"); } },
                { "possibleValues", n => { PossibleValues = n.GetCollectionOfPrimitiveValues<string>()?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'PossibleValues'"); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "valueType", n => { ValueType = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.FieldType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteBoolValue("canBeNegative", CanBeNegative);
            writer.WriteGuidValue("fieldVersionId", FieldVersionId);
            writer.WriteBoolValue("isRequired", IsRequired);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("orderNumber", OrderNumber);
            writer.WriteCollectionOfPrimitiveValues<string>("possibleValues", PossibleValues);
            writer.WriteStringValue("value", Value);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.FieldType>("valueType", ValueType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
