// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Model for an item field in a projects settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class ItemFieldModel : IParsable
    {
        /// <summary>Is this field required to have a value?</summary>
        public bool IsRequired { get; set; } = default!;
        /// <summary>Internal ID for the ItemField</summary>
        public Guid ItemFieldId { get; set; } = default!;
        /// <summary>Internal ID for the current version ItemFieldVersion</summary>
        public Guid ItemFieldLatestVersionId { get; set; } = default!;
        /// <summary>The name of this ItemField</summary>
        public string Name { get; set; } = default!;
        /// <summary>The type property</summary>
        public global::Bones.Api.Client.AutoGen.Models.FieldType? Type { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.ItemFieldModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.ItemFieldModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.ItemFieldModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "isRequired", n => { IsRequired = n.GetBoolValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'IsRequired'"); } },
                { "itemFieldId", n => { ItemFieldId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ItemFieldId'"); } },
                { "itemFieldLatestVersionId", n => { ItemFieldLatestVersionId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ItemFieldLatestVersionId'"); } },
                { "name", n => { Name = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Name'"); } },
                { "type", n => { Type = n.GetEnumValue<global::Bones.Api.Client.AutoGen.Models.FieldType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isRequired", IsRequired);
            writer.WriteGuidValue("itemFieldId", ItemFieldId);
            writer.WriteGuidValue("itemFieldLatestVersionId", ItemFieldLatestVersionId);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Bones.Api.Client.AutoGen.Models.FieldType>("type", Type);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
