// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>The use for which this layout is intended</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    public enum ItemLayoutUse
    {
        [EnumMember(Value = "None")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "Tasks")]
        #pragma warning disable CS1591
        Tasks,
        #pragma warning restore CS1591
        [EnumMember(Value = "Assets")]
        #pragma warning disable CS1591
        Assets,
        #pragma warning restore CS1591
    }
}
