// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Request to login
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class LoginUserApiRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The users email address</summary>
        public string Email { get; set; } = default!;
        /// <summary>The users password</summary>
        public string Password { get; set; } = default!;
        /// <summary>If they have 2fa, include the code here</summary>
        public string? TwoFactorCode { get; set; } = default!;
        /// <summary>If they have 2fa and can&apos;t use their authenticator, include a recovery code here</summary>
        public string? TwoFactorRecoveryCode { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.LoginUserApiRequest"/> and sets the default values.
        /// </summary>
        public LoginUserApiRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.LoginUserApiRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.LoginUserApiRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.LoginUserApiRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Email'"); } },
                { "password", n => { Password = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Password'"); } },
                { "twoFactorCode", n => { TwoFactorCode = n.GetStringValue(); } },
                { "twoFactorRecoveryCode", n => { TwoFactorRecoveryCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("twoFactorCode", TwoFactorCode);
            writer.WriteStringValue("twoFactorRecoveryCode", TwoFactorRecoveryCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
