// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Represents an audit of a user account
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class MyAccountAuditModel : IParsable
    {
        /// <summary>The action that took place</summary>
        public string Action { get; set; } = default!;
        /// <summary>Who is responsible for the action</summary>
        public string ActionBy { get; set; } = default!;
        /// <summary>The date and time the action was taken</summary>
        public DateTimeOffset DateTime { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.MyAccountAuditModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Action'"); } },
                { "actionBy", n => { ActionBy = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'ActionBy'"); } },
                { "dateTime", n => { DateTime = n.GetDateTimeOffsetValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'DateTime'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("actionBy", ActionBy);
            writer.WriteDateTimeOffsetValue("dateTime", DateTime);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
