// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    #pragma warning disable CS1591
    public enum ProjectPreset
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "development")]
        #pragma warning disable CS1591
        Development,
        #pragma warning restore CS1591
        [EnumMember(Value = "test")]
        #pragma warning disable CS1591
        Test,
        #pragma warning restore CS1591
    }
}
