// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    #pragma warning disable CS1591
    public enum SelectionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "single")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
        [EnumMember(Value = "multiple")]
        #pragma warning disable CS1591
        Multiple,
        #pragma warning restore CS1591
    }
}
