// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>The selection type for this assignee slot, single or multiple</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0")]
    public enum SelectionType
    {
        [EnumMember(Value = "Single")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
        [EnumMember(Value = "Multiple")]
        #pragma warning disable CS1591
        Multiple,
        #pragma warning restore CS1591
    }
}
