// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    #pragma warning disable CS1591
    public partial class StringStringListKeyValuePair : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The key property</summary>
        public string? Key { get; set; } = default!;
        /// <summary>The value property</summary>
        public List<string> Value { get; set; } = default!;
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.StringStringListKeyValuePair"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.StringStringListKeyValuePair CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Bones.Api.Client.AutoGen.Models.StringStringListKeyValuePair();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "key", n => { Key = n.GetStringValue(); } },
                { "value", n => { Value = n.GetCollectionOfPrimitiveValues<string>()?.AsList() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'Value'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("key", Key);
            writer.WriteCollectionOfPrimitiveValues<string>("value", Value);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
