// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Bones.Api.Client.AutoGen.Models
{
    /// <summary>
    /// Model for the  queues to be listed in an initiative
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.6")]
    public partial class TaskQueueListModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; } = default!;
        /// <summary>The number of s in the  queue</summary>
        public int TaskCount { get; set; } = default!;
        /// <summary>The  queue ID</summary>
        public Guid TaskQueueId { get; set; } = default!;
        /// <summary>The name of the  queue</summary>
        public string TaskQueueName { get; set; } = default!;
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Models.TaskQueueListModel"/> and sets the default values.
        /// </summary>
        public TaskQueueListModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Models.TaskQueueListModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Bones.Api.Client.AutoGen.Models.TaskQueueListModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            ArgumentNullException.ThrowIfNull(parseNode);
            return new global::Bones.Api.Client.AutoGen.Models.TaskQueueListModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "taskCount", n => { TaskCount = n.GetIntValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'TaskCount'"); } },
                { "taskQueueId", n => { TaskQueueId = n.GetGuidValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'TaskQueueId'"); } },
                { "taskQueueName", n => { TaskQueueName = n.GetStringValue() ?? throw new NullReferenceException("Unexpected null value for non-nullable property: 'TaskQueueName'"); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            ArgumentNullException.ThrowIfNull(writer);
            writer.WriteIntValue("taskCount", TaskCount);
            writer.WriteGuidValue("taskQueueId", TaskQueueId);
            writer.WriteStringValue("taskQueueName", TaskQueueName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
