// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Item;
using Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Latest;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.GenericItem.Layouts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \GenericItem\layouts\{layoutId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class WithLayoutItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The latest property</summary>
        public global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Latest.LatestRequestBuilder Latest
        {
            get => new global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Bones.Api.Client.AutoGen.GenericItem.layouts.item.item collection</summary>
        /// <param name="position">The version if you want a specific version instead of the latest</param>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Item.WithRequestedVersionItemRequestBuilder"/></returns>
        public global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Item.WithRequestedVersionItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("requestedVersion", position);
                return new global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.Item.WithRequestedVersionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.WithLayoutItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLayoutItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/GenericItem/layouts/{layoutId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.GenericItem.Layouts.Item.WithLayoutItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLayoutItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/GenericItem/layouts/{layoutId}", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
