namespace Bones.WebUI;

/// <summary>
///   The main application class for the Bones WebUI.
/// </summary>
/// <remarks>
///   This code behind isn't really needed, it'll be generated by the compiler.
///   But VS Code can't seem to figure that out and will just show a consistent error on Program.cs unless this is here.
/// </remarks>
public partial class App : ComponentBase;
