<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <!-- Build info -->
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <PublishTrimmed>false</PublishTrimmed>

        <!-- Assembly info -->
        <VersionPrefix>0.0.1</VersionPrefix>
        <VersionSuffix>$(SourceRevisionId)</VersionSuffix>
        <Authors>Nickolas Gupton</Authors>
        <RepositoryUrl>https://github.com/CorruptComputer/Bones</RepositoryUrl>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <SourceControlInformationFeatureSupported>true</SourceControlInformationFeatureSupported>
        <SourceRevisionId>develop</SourceRevisionId>
        <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
        <!-- Recommended for mobile browsers: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-8.0#decrease-maximum-heap-size-for-some-mobile-device-browsers -->
        <EmccMaximumHeapSize>268435456</EmccMaximumHeapSize>
    </PropertyGroup>

    <!-- This seems like it could be useful -->
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <!-- If building in release mode, replace the SourceRevisionId with the 8 character git commit hash -->
    <Target Condition="$(Configuration) == 'Release'" Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
        <Exec Command="git describe --long --always --dirty --exclude=* --abbrev=8" ConsoleToMSBuild="True" IgnoreExitCode="False">
            <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
        </Exec>
    </Target>

    <ItemGroup Condition="$(Configuration) == 'Debug'">
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.10" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.10" />
        <PackageReference Include="MudBlazor" Version="8.14.0" />
        <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="8.2.5" />
    </ItemGroup>

    <ItemGroup>
        <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\Bones.Api.Client\Bones.Api.Client.csproj" />
        <ProjectReference Include="..\Bones.WebUI.Leaflet\Bones.WebUI.Leaflet.csproj" />
        <ProjectReference Include="..\Bones.WebUI.SubtleCrypto\Bones.WebUI.SubtleCrypto.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Sdk.WebAssembly.Pack" Version="9.0.10" />
        <Content Remove="wwwroot\appsettings.Development.json" Condition="$(Configuration) == 'Release'" />
    </ItemGroup>

</Project>
