name: .NET Build & Test

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_ENVIRONMENT: "Development"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Print .NET version
        run: |
          dotnet --version
          dotnet --list-sdks

      - name: Restore Tools
        run: |
          cd Services/Bones.Api
          dotnet tool restore
          cd ../..
          cd Services/Bones.BackgroundService
          dotnet tool restore
          cd ../..
          cd Frontend/Bones.Api.Client
          dotnet tool restore
          cd ../..

      - name: Build
        run: |
          dotnet build --configuration Debug --no-incremental
          git diff --quiet || exit 1

      - name: Test
        run: dotnet test --no-build