name: .NET Build & Test

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_ENVIRONMENT: "Development"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/workflows/setup-env

      - name: Build
        run: |
          dotnet build --configuration Debug --no-incremental
          git diff --quiet || exit 1

      - name: Test
        run: dotnet test --no-build