name: Build Server Artifacts

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  server:
    name: Publish Server
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build API Packages
        run: |
          cd Backend/Bones.Api
          dotnet tool restore
          dotnet deb --configuration Release --output ../../publish-api/
          dotnet rpm --configuration Release --output ../../publish-api/
          cd ../..

      - name: Build Background Service Packages
        run: |
          cd Backend/Bones.BackgroundService
          dotnet tool restore
          dotnet deb --configuration Release --output ../../publish-background-service/
          dotnet rpm --configuration Release --output ../../publish-background-service/
          cd ../..

      - name: Upload API DEB Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/publish-api/*.deb
      
      - name: Upload API RPM Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/publish-api/*.rpm
          
      - name: Upload Background Service DEB Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/publish-background-service/*.deb
          
      - name: Upload Background Service RPM Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ~/publish-background-service/*.rpm