name: Build Server Artifacts

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  server:
    name: Publish Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      BonesBackendConfiguration__UseInMemoryDb: true
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_ENVIRONMENT: "Development"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build Packages
        run: |
          shipyard --config ./Services/Bones.Api/shipyard.json --output ./publish-api
          shipyard --config ./Services/Bones.BackgroundService/shipyard.json --output ./publish-backgroundservice
          mkdir ./publish
          mv ./publish-api/*.rpm ./publish/
          mv ./publish-backgroundservice/*.rpm ./publish/

      #- name: Upload DEB Build Artifacts
      #  uses: actions/upload-artifact@v6
      #  with:
      #    name: 'Server DEB build.zip'
      #    path: ./publish/*.linux-x64.deb

      - name: Upload RPM Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: 'Server RPM build.zip'
          path: ./publish/*.rpm
