name: Build Server Artifacts

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  server:
    name: Publish Server
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
    steps:
      - uses: ./.github/actions/setup-env

      - name: Build API Packages
        run: |
          cd Services/Bones.Api
          dotnet deb --configuration Release --version-suffix commit --output ../../publish/
          dotnet rpm --configuration Release --version-suffix commit --output ../../publish/
          cd ../..

      - name: Build Background Service Packages
        run: |
          cd Services/Bones.BackgroundService
          dotnet deb --configuration Release --version-suffix commit --output ../../publish/
          dotnet rpm --configuration Release --version-suffix commit --output ../../publish/
          cd ../..

      - name: Upload DEB Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'Server DEB build.zip'
          path: ./publish/*.linux-x64.deb
      
      - name: Upload RPM Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'Server RPM build.zip'
          path: ./publish/*.linux-x64.rpm
          