name: Build Client Artifact

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'

jobs:
  client:
    name: Publish Client
    runs-on: ubuntu-latest
    env:
      DatabaseConfiguration__UseInMemoryDb: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache .NET
        uses: actions/cache@v4
        with:
          path: /usr/share/dotnet
          key: dotnet
          restore-keys: dotnet

      - name: Cache .NET Tools
        uses: actions/cache@v4
        with:
          path: ~/.dotnet
          key: dotnet-tools
          restore-keys: dotnet-tools

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Tools
        run: |
          cd Frontend/Bones.Api.Client
          dotnet tool restore
          cd ../..
          cd Frontend/Bones.WebUI
          dotnet workload restore
          cd ../..

      - name: Publish
        run: |
          cd Frontend/Bones.WebUI
          dotnet publish Bones.WebUI.csproj --configuration Release --property PublishDir=../../publish/
          cd ../..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webui-wasm-client
          path: ./publish