// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Account.Item.PublicProfile;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Bones.Api.Client.AutoGen.Account.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \Account\{bonesUserId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.2")]
    public partial class WithBonesUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The publicProfile property</summary>
        public global::Bones.Api.Client.AutoGen.Account.Item.PublicProfile.PublicProfileRequestBuilder PublicProfile
        {
            get => new global::Bones.Api.Client.AutoGen.Account.Item.PublicProfile.PublicProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.Item.WithBonesUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBonesUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/{bonesUserId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.Item.WithBonesUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithBonesUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/{bonesUserId}", rawUrl)
        {
        }
    }
}
#nullable restore
#pragma warning restore CS0618
