// <auto-generated/>
#pragma warning disable CS0618
#nullable enable
using Bones.Api.Client.AutoGen.Models;
using ReQuesty.Runtime.Abstractions.Serialization;
using ReQuesty.Runtime.Abstractions;
using ReQuesty.Runtime.Extensions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Bones.Api.Client.AutoGen.Account.My.Password
{
    /// <summary>
    /// Builds and executes requests for operations under \Account\my\password
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ReQuesty", "0.0.1")]
    public partial class PasswordRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.My.Password.PasswordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasswordRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/my/password", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Bones.Api.Client.AutoGen.Account.My.Password.PasswordRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PasswordRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/Account/my/password", rawUrl)
        {
        }
        /// <summary>
        /// Updates the current users password
        /// </summary>
        /// <returns>A <see cref="bool"/></returns>
        /// <param name="body">Request for the ChangeMyPasswordAsync endpoint</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Bones.Api.Client.AutoGen.Models.ErrorResponse">When receiving a 500 status code</exception>
        public async Task<bool?> PutAsync(global::Bones.Api.Client.AutoGen.Models.ChangeMyPasswordRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Bones.Api.Client.AutoGen.Models.ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<bool>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the current users password
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request for the ChangeMyPasswordAsync endpoint</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        public RequestInformation ToPutRequestInformation(global::Bones.Api.Client.AutoGen.Models.ChangeMyPasswordRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Bones.Api.Client.AutoGen.Account.My.Password.PasswordRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Bones.Api.Client.AutoGen.Account.My.Password.PasswordRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Bones.Api.Client.AutoGen.Account.My.Password.PasswordRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#nullable restore
#pragma warning restore CS0618
